const CHARACTER_CARDS = { #FAMA - ATTACK - DEFFENSE - TYPE
	"Restless Gambler": 	[2, 2, 2, CARD_TYPE.APPRENTICE_HERO],
	"Mila Muzari": 			[2, 1, 3, CARD_TYPE.APPRENTICE_HERO],
	"Building Looker": 		[2, 3, 1, CARD_TYPE.APPRENTICE_HERO],
	"Barnie Steel": 		[2, 0, 4, CARD_TYPE.APPRENTICE_HERO],
}

const SUPPORT_CARDS = { #FAMA - TYPE
	"": [3, CARD_TYPE.LESSON]
}

enum CARD_STATS {
	FAMA = 0,
	ATTACK = 1,
	DEFFENSE = 2,
	TYPE = 3,
}

enum CARD_TYPE {
	#PROTAGONIST,
	PROFESSIONAL_HERO,
	APPRENTICE_HERO,
	VILLAIN,
	LESSON,
	EVENT,
	UPGRADE,
}
